python train.py\
 --width=300\
 --height=200\
 --gpus $1,\
 --num_workers=4\
 --batch_size=16\
 --max_epochs 50\
 --patience 10\
 --lr 3e-5\
 --data_dir "../../data"\
 --encoder ResNet-18\
 --dataset "Talk2Car_Detector"\
 --use_ref_obj\
 --save_dir "checkpoint"\
 --gaussian_size 11\
 --gaussian_sigma 3